pipeline {
    agent any
    tools {
        maven 'Maven_Home' 
        jdk 'Java_Home'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver Script') { 
            steps {
                // Runs the official tutorial script
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('Run on EC2') {
            steps {
                // JENKINS_NODE_COOKIE prevents Jenkins from killing the process
                sh 'JENKINS_NODE_COOKIE=dontKillMe nohup java -jar target/my-app-1.0-SNAPSHOT.jar > app.log 2>&1 &'
                echo "Application is starting in the background..."
            }
        }
    }
}
